MIGRATION_MSG?=autogenerated
REVISION?=head
DOWNGRADE_STEP?=-1

DC=docker-compose

install:
	ls .venv || python -m venv .venv
	source .venv/bin/activate
	pip install -r requirements.txt
	mkdir -p data alembic/versions
	make build

build:
	$(DC) build

backend:
	$(DC) up -d --build backend

run:
	$(DC) up -d --build

down:
	$(DC) down

revision:
	$(DC) exec backend sh -c "alembic revision --autogenerate -m '$(MIGRATION_MSG)'"

migrate: backend
	$(DC) exec backend sh -c "alembic upgrade $(REVISION)"

downgrade:
	$(DC) exec backend sh -c "alembic downgrade $(DOWNGRADE_STEP)"

logs:
	$(DC) logs -f backend

clean:
	$(DC) down --rmi all --volumes --remove-orphans

test:
	python -m pytest tests/

.PHONY: \
	install build backend run down \
	revision migrate downgrade \
	logs clean test
