MIGRATION_MSG?=autogenerated
REVISION?=head
DOWNGRADE_STEP?=-1

VENV=.venv
PIP=.venv/bin/pip
DC=docker-compose

install:
	test -d $(VENV) || python3 -m venv $(VENV)
	$(PIP) install --upgrade pip
	$(PIP) install -r requirements.txt
	mkdir -p data alembic/versions
	$(MAKE) build

build:
	$(DC) build

backend:
	$(DC) up -d --build backend

run:
	$(DC) up -d --build

down:
	$(DC) down

revision:
	$(DC) exec backend alembic revision --autogenerate -m "$(MIGRATION_MSG)"

migrate: backend
	$(DC) exec backend alembic upgrade $(REVISION)

downgrade:
	$(DC) exec backend alembic downgrade $(DOWNGRADE_STEP)

logs:
	$(DC) logs -f backend

clean:
	$(DC) down --volumes --remove-orphans

test:
	python -m pytest tests/

.PHONY: \
	install build backend run down \
	revision migrate downgrade \
	logs clean test
