from enum import Enum


class TemplateName(str, Enum):
    WELCOME_EMAIL = "WELCOME_EMAIL"
    BANK_LINK_NUDGE_SMS = "BANK_LINK_NUDGE_SMS"
    INSUFFICIENT_FUNDS_EMAIL = "INSUFFICIENT_FUNDS_EMAIL"
    HIGH_RISK_ALERT = "HIGH_RISK_ALERT"
